compression: Zstd
index_attributes:
  default_fields: ['title', 'body']
  unique_fields: ['url']
index_engine:
  ipfs:
    chunked_cache_config:
      chunk_size: 16384
      cache_size: 134217728
index_name: meduza
merge_policy:
  log:
    is_frozen: false
schema:
- name: locale
  type: text
  options:
    indexing:
      fieldnorms: false
      record: basic
      tokenizer: raw
    stored: true
- name: url
  type: text
  options:
    indexing:
      fieldnorms: false
      record: basic
      tokenizer: raw
    stored: true
- name: title
  type: text
  options:
    indexing:
      fieldnorms: true
      record: position
      tokenizer: summa
    stored: true
- name: body
  type: text
  options:
    indexing:
      fieldnorms: true
      record: position
      tokenizer: summa
    stored: true
- name: tags
  type: text
  options:
    indexing:
      fieldnorms: true
      record: basic
      tokenizer: default
    stored: true
- name: published_at
  type: i64
  options:
    fast: single
    fieldnorms: false
    indexed: true
    stored: true
- name: document_type
  type: text
  options:
    indexing:
      fieldnorms: false
      record: basic
      tokenizer: raw
    stored: true
sort_by_field: ["published_at", "Desc"]